version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
        - "5000:5000"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example